### ISSUE TITLE
backspace not work in build

### ISSUE THREAD

**Issue by ifooth** [indygreg/python-build-standalone#28] opened 2020-02-06 02:42 UTC
### Version
- cpython-3.7.5-linux64-musl-20191026T0603.tar.zst

### Question
![image](https://user-images.githubusercontent.com/1853121/73901221-15d50900-48cd-11ea-97e3-400d81c751d2.png)

test by centos and alpine, same issue

**Comment by indygreg** [comment] 2020-02-09 16:58
This is because the `readline` Python package / C library can't find the `terminfo` database. This is because the default location of this database is compiled into the library and the location used when building these distributions doesn't agree with your local machine. You can work around this by setting the `TERMINFO_DIRS` environment variable to the location of your `terminfo` database. See https://github.com/indygreg/PyOxidizer/blob/main/pyembed/src/osutils.rs for how PyOxidizer does this.

FWIW what happens when you press the backspace key is that readline+terminfo combine to translate that to a terminal control code sequence that deletes the last character and moves the cursor backward. Without the terminfo database telling things how to translate the key press to special activity, the key press is registered as a normal key press, which results in it being printed. That's why the cursor advances.

The behavior here is somewhat "works as intended." Did you have a resolution in mind for this issue? Better documentation perhaps?

**Comment by ntoll** [comment] 2020-04-11 21:33
FWIW, here's a "written out" example for how to do it on a Debian based version of Linux:

```
$ TERMINFO_DIRS=/etc/terminfo:/lib/terminfo:/usr/share/terminfo ./python3.7m
```

Take the relevant value for your flavour of unix from the linker-to Rust code referenced above.

**Comment by indygreg** [comment] 2020-04-12 20:30
I've documented this quirk, as can be seen at https://python-build-standalone.readthedocs.io/en/latest/quirks.html#backscape-key-doesn-t-work-in-python-repl.

I believe when I looked at distributing a terminfo database with the distribution that it was non-trivial to get the libraries to actually detect it without either an environment variable or custom code call the C API to tell it where it was. So our current state of affairs may sadly be the best we can do. Therefore, I'm closing this issue.

**Closed by indygreg** 2020-04-12 20:30 UTC
