### ISSUE TITLE
New Release Tracker (to pick up ppc64le support)

### ISSUE THREAD

**Issue by clnperez** [indygreg/python-build-standalone#171] opened 2023-04-25 14:54 UTC
Since Power support was merged, I'm requesting a new release be created so we can pick that up. 

Background: https://github.com/indygreg/python-build-standalone/pull/165#issuecomment-1520784714

Thanks again @indygreg. Very much appreciated!

**Comment by indygreg** [comment] 2023-05-01 00:35
Dupe of #170. (First issue wins I guess.)

**Closed by indygreg** 2023-05-01 00:35 UTC
