### ISSUE TITLE
Please support Apple silicon (M1, arm64-darwin)

### ISSUE THREAD

**Issue by zoain-it** [indygreg/python-build-standalone#64] opened 2020-12-28 07:47 UTC
Hello!
it would be great if [python-build-standalone](https://github.com/indygreg/python-build-standalone) could support arm64-darwin (the new Mac M1 SoC)

Thanks!

**Comment by indygreg** [comment] 2020-12-28 15:34
It's on my TODO list. I don't yet have access to Apple silicon, however. But cross-compiling should be possible. But without access to Apple silicon, I won't have a way to test, so that makes it difficult. I'll probably end up buying an M1 Apple machine in the next several months.

**Comment by zoain-it** [comment] 2020-12-29 01:35
What can I do to help, maybe I can provide tests. Also I tried to add aarch64 support locally but when compiling bdb, I found that bdb doesn't seem to have a version for aarch64 yet.

**Comment by indygreg** [comment] 2021-01-16 21:55
I just pushed a commit to switch from our custom BerkeleyDB to the DBM that ships with macOS and is part of `libSystem`. So this should hopefully remove one build blocker!

**Comment by indygreg** [comment] 2021-01-18 19:20
I just pushed some commits to the `main` branch that seem to get a cross-compiled Python targeting Apple M1 silicon built. However, I don't yet have access to an M1 machine and can't verify things work. I anticipate that code signing doesn't work, as I don't believe Python's build system integrates code signing. Beyond that, I'm not sure.

You can build your own distribution via `./build-macos.py --target-triple aarch64-apple-darwin --python cpython-3.9`. Ideally we'd get CI hooked up so others can try binaries it produces. Unsure when I'll do this.

I'm sure there are plenty of issues with the built distribution. I really need access to M1 hardware to put it through its paces. Unfortunately, the model I want isn't in stock at Apple stores and I'm currently traveling and don't know where to ship a laptop. So it could be several weeks before I have my own M1.

In the mean time, please try to build your own distribution and let me know what isn't working!

**Comment by zoain-it** [comment] 2021-01-18 23:43
Okay, I'll try it. This is great, thanks for your work!

**Comment by zoain-it** [comment] 2021-01-18 23:52
I tried to start the build, but after entering the command, nothing happened, except that the build folder was generated

**Comment by zoain-it** [comment] 2021-01-19 00:20
I installed a python using brew and am compiling it now. Why can't I use the python that comes with the system

**Comment by zoain-it** [comment] 2021-01-19 00:21
I get it, this is really great. It's very clean.

**Comment by zoain-it** [comment] 2021-01-19 01:20
<img width="727" alt="image" src="https://user-images.githubusercontent.com/43292634/104976093-59ba1300-5a37-11eb-823a-244810c71b45.png">
ld: library not found for -lSystem
What is the "System" library?

**Comment by zoain-it** [comment] 2021-01-19 08:49
<img width="730" alt="image" src="https://user-images.githubusercontent.com/43292634/105009914-0c10cb00-5a76-11eb-8759-9e13847da7d2.png">
I compiled to the point where I couldn't proceed further. By the way, maybe our llvm needs to be upgraded, the 11.0.0 we are using now seems to have some problems compiling. I replaced it with the 12 that comes with the system and it's fine.

**Comment by zoain-it** [comment] 2021-01-19 09:01
[diff.zip](https://github.com/indygreg/python-build-standalone/files/5834773/diff.zip)
I compiled to the current diff file

**Comment by zoain-it** [comment] 2021-01-19 13:33
> <img alt="image" width="727" src="https://user-images.githubusercontent.com/43292634/104976093-59ba1300-5a37-11eb-823a-244810c71b45.png">
> 
> ld: library not found for -lSystem What is the "System" library?

For the current progress of the project, it is still stuck in this

**Comment by indygreg** [comment] 2021-02-06 17:14
I've purchased an M1 machine and it will arrive in 2-3 weeks. I anticipate having M1 builds working shortly thereafter.

**Comment by indygreg** [comment] 2021-02-20 18:31
This comment was sent through my new M1 Mac mini. I'm looking forward to getting M1 builds working soon!

**Comment by indygreg** [comment] 2021-02-21 00:14
`./build-macos.py` should now work on an M1 device.

I still need to sort through getting cross-compiled builds to work, as this will be needed to produce release artifacts via GitHub Actions until GitHub gives us access to M1 hardware. Although if I'm really desperate, I could turn my Mac mini into a self-hosted GitHub Actions runner. Although I'd prefer to not do that given security implications.

**Comment by indygreg** [comment] 2021-02-21 01:16
I was able to run `install/bin/python3.9` on an M1 Mac mini from a build produced on Intel hardware:

```
% python/install/bin/python3.9
Python 3.9.2 (default, Feb 20 2021, 17:06:00)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, sysconfig
>>> platform.machine()
'arm64'
>>> sysconfig.get_config_var("BUILD_GNU_TYPE")
'x86_64-apple-darwin18.7.0'
```

This is on a brand new Mac mini. I haven't done anything special: just installed Xcode, Homebrew, etc to get a development environment up.

Is anyone else able to reproduce my success?

**Comment by zoain-it** [comment] 2021-02-21 10:24
> I was able to run `install/bin/python3.9` on an M1 Mac mini from a build produced on Intel hardware:
> 
> ```
> % python/install/bin/python3.9
> Python 3.9.2 (default, Feb 20 2021, 17:06:00)
> [Clang 11.0.1 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import platform, sysconfig
> >>> platform.machine()
> 'arm64'
> >>> sysconfig.get_config_var("BUILD_GNU_TYPE")
> 'x86_64-apple-darwin18.7.0'
> ```
> 
> This is on a brand new Mac mini. I haven't done anything special: just installed Xcode, Homebrew, etc to get a development environment up.
> 
> Is anyone else able to reproduce my success?

Is this cross-compiled with an intel machine?

**Comment by indygreg** [comment] 2021-02-21 16:40
Yes, it is with cross-compiling from macOS 11.1. Native builds should also work.

CI is still broken. But I think I know what the problem is and that should hopefully be fixed soon.

**Comment by zoain-it** [comment] 2021-02-21 23:59
You can try a local build, I've had problems with local builds before

**Comment by indygreg** [comment] 2021-02-22 22:18
The CI cross build from an x86_64 macOS 10.15 machine to aarch64 (M1) macOS 11.0+ is now working!

Until GitHub gives us M1 workers for GitHub Actions, we aren't able to produce a PGO optimized build via GitHub Actions. But since I have an M1 machine now, I can manually produce a PGO build at release time.

Since I believe aarch64 Darwin support is now implemented and working, I'm going to close this issue. Please open a new issue if you find any bugs or unexpected behavior in these builds.

**Closed by indygreg** 2021-02-22 22:18 UTC
Labels: enhancement

**Comment by zoain-it** [comment] 2021-02-23 08:25
Thank you, thank you very much for your work
