### ISSUE TITLE
Avoid hard-coded URL's

### ISSUE THREAD

**Issue by khaledismaeel** [indygreg/python-build-standalone#130] opened 2022-05-21 03:19 UTC
I've been trying to build the project with
``` bash
$ ./build-linux.py --target x86_64-unknown-linux-musl
```
And the build failed with the following error (I'll avoid spamming the whole output here):
```
image-build> W: Failed to fetch http://snapshot.debian.org/archive/debian/20220429T205342Z/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 193.62.202.27 80]
```
Besides the following:
```
Traceback (most recent call last):
  File "/home/khaledismaeel/python-build-standalone/cpython-unix/build.py", line 1159, in <module>
    sys.exit(main())
  File "/home/khaledismaeel/python-build-standalone/cpython-unix/build.py", line 976, in main
    build_docker_image(client, image_data, BUILD, image_name)
  File "/home/khaledismaeel/python-build-standalone/pythonbuild/docker.py", line 35, in build_docker_image
    return ensure_docker_image(client, io.BytesIO(image_data), image_path=image_path)
  File "/home/khaledismaeel/python-build-standalone/pythonbuild/docker.py", line 52, in ensure_docker_image
    raise Exception("unable to determine built Docker image")
Traceback (most recent call last):
  File "/home/khaledismaeel/python-build-standalone/cpython-unix/build.py", line 1159, in <module>
Exception: unable to determine built Docker image
    sys.exit(main())
  File "/home/khaledismaeel/python-build-standalone/cpython-unix/build.py", line 976, in main
    build_docker_image(client, image_data, BUILD, image_name)
  File "/home/khaledismaeel/python-build-standalone/pythonbuild/docker.py", line 35, in build_docker_image
    return ensure_docker_image(client, io.BytesIO(image_data), image_path=image_path)
  File "/home/khaledismaeel/python-build-standalone/pythonbuild/docker.py", line 52, in ensure_docker_image
    raise Exception("unable to determine built Docker image")
Exception: unable to determine built Docker image
make: *** [Makefile:71: /home/khaledismaeel/python-build-standalone/build/image-xcb.tar] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:71: /home/khaledismaeel/python-build-standalone/build/image-build.tar] Error 1
```

Indeed, the URL does not exist. I noticed it in code [here](https://github.com/indygreg/python-build-standalone/blob/2b425adb1013362061dfe38c7c1b2d5febb5ff80/cpython-unix/base.Dockerfile#L21) and [here](https://github.com/indygreg/python-build-standalone/blob/2b425adb1013362061dfe38c7c1b2d5febb5ff80/cpython-unix/build.cross.Dockerfile#L21).

Though to be honest I don't know the idiomatic way of dealing with this.

**Comment by indygreg** [comment] 2022-05-21 15:36
We use snapshot.debian.org so we have reproducible container images to perform builds so the entire build process is highly deterministic.

That service has hiccups periodically. It looks like they're having one now. This is the price we pay for reproducibility, sadly.

I'm not inclined to spend the effort to cache these images unless downtime becomes more common. So closing this issue as non-actionable.

**Closed by indygreg** 2022-05-21 15:36 UTC
