### ISSUE TITLE
Fedora 35(x64), error while loading shared libraries: libcrypt.so.1

### ISSUE THREAD

**Issue by bigcat88** [indygreg/python-build-standalone#113] opened 2022-02-17 09:16 UTC
Good project, thanks you for it.

Have a problem(subj).
When do what here proposed it starts working: [missing-libcrypt-so-1-library-on-fedora](https://tex.stackexchange.com/questions/493231/biber-missing-libcrypt-so-1-library-on-fedora)
But the main goal to install everything without root privileges.

A bit more info: [fedoraproject: Replace glibc libcrypt with libxcrypt](https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt)

Is here can be any workaround? Or the only way is to build separate version for last two Fedora's?

**Comment by indygreg** [comment] 2022-02-18 01:06
Note that there is prior history with `libcrypt.so.1` and this project: https://github.com/indygreg/PyOxidizer/issues/89.

It is still an unsolved problem. I suspect that in the wild a lot of users have `libxcrypt-compat` installed for various reasons.

FWIW in Fedora 35, `libcrypt.so.2` and `libcrypt.so.2.0.0` are installed by default. The `libxcrypt-compat` package provides `libcrypt.so.1` and `libcrypt.so.1.1.0`.

I'll repeat what I said in the old PyOxidizer issue that the Linux Standard Base Core Specification defines `libcrypt.so.1` as containing the API for libcrypt (https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-AMD64/LSB-Core-AMD64/libcrypt.html). So on casual glance it looks like Fedora is in violation of the LSB by not providing a `libcrypt.so.1` by default.

The reason this matters is because the LSB defines an interface that projects like this can target with reasonable guarantees of cross-distro compatibility. And by not conforming with the LSB, Fedora is essentially foregoing that compatibility.

From my perspective, my preference would be for Fedora to be compliant with the LSB Core Specification and provide a `libcrypt.so.1` out-of-the-box. What actually provides that file, I don't care: it just needs to exist and provide the interfaces as defined by the LSB.

An alternative solution is to provide a Python build that doesn't depend on `libcrypt.so.1`. That would entail disabling the `_crypt` extension module, which would remove (all?) functionality from the [crypt](https://docs.python.org/3/library/crypt.html) module. That might be doable. FWIW we already disabled the `nis` extension module in #51 for similar Fedora/RHEL support reasons. Although `libnis` isn't defined by the LSB, so this was an easier decision.

At the very least we should document this quirk and its current workaround.

**Comment by indygreg** [comment] 2022-02-18 01:19
On audit of the `_crypt` Python extension module, it calls `crypt_r` or `crypt` if `crypt_r` is not available. The availability of `cyrpt_r` is a configure-time check. https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-AMD64/LSB-Core-AMD64/libcrypt.html says both of these functions are in `libcrypt`.

If CPython were relying on functions not defined by the LSB, that would be grounds to remove the functionality. But since the functions it uses are defined by the LSB Core Specification, I don't believe CPython or this project are in the wrong in their dependence on `libcrypt.so.1`.

**Comment by indygreg** [comment] 2022-02-18 01:27
See also https://github.com/pantsbuild/pants/issues/7369#issuecomment-1043486639 and https://patchwork.ozlabs.org/project/glibc/patch/20170829184247.6875-1-zackw@panix.com/.

It looks like glibc deprecated libcrypt back in 2017. So I guess glibc is the cause of Linux distros being incompatible with the LSB Core Specification?!

Standards. 🤷‍♂️

**Comment by indygreg** [comment] 2022-02-18 01:30
If glibc did in fact delete libcrypt and distros are providing `libcrypt.so.1` through some other implementation [to remain compliant with the LSB], that pushes me towards disabling the `_crypt` Python extension module by default. But I still wish I could rely on the LSB... because standards.

**Comment by indygreg** [comment] 2022-02-18 16:35
﻿Filed https://bugzilla.redhat.com/show_bug.cgi?id=2055953 against Fedora and at this time they seem to acknowledge that this is a legit distro bug.

**Comment by indygreg** [comment] 2022-07-31 19:08
Looks like a fix was committed a few weeks ago. So closing this issue. Will also push a commit adding documentation about this quirk later today.

**Closed by indygreg** 2022-07-31 19:08 UTC
Labels: bug
